/**
 * Utility functions for math normalization and LaTeX sanitization.
 */

/**
 * Fixes common malformed LaTeX generated by AI models and ensures robust formatting for KaTeX.
 */
export const normalizeLatex = (text: string): string => {
  if (!text) return '';

  let sanitized = text;

  // 1. Basic cleaning and sanitization (Preserve newlines but normalize them)
  sanitized = sanitized
    .replace(/```[a-z]*\n?/g, '') // Strip markdown code blocks
    .replace(/```/g, '')
    .replace(/\r\n/g, '\n')
    .replace(/\n\r/g, '\n');

  // 2. Uniform delimiters (\( -> $, \[ -> $$) but only if not already mixed
  // We'll keep them as they are to let MathRenderer handle them, 
  // but we fix common spacing issues.
  sanitized = sanitized.replace(/\\ \(/g, '\\(').replace(/\\ \)/g, '\\)');
  sanitized = sanitized.replace(/\\ \[/g, '\\[').replace(/\\ \]/g, '\\]');

  // 3. Fix common LaTeX command spacing and short commands
  const mathSymbols = ['text', 'sin', 'cos', 'tan', 'cot', 'sec', 'csc', 'log', 'ln', 'sqrt', 'frac', 'theta', 'alpha', 'beta', 'gamma', 'delta', 'pi', 'phi', 'omega', 'sigma', 'lambda', 'times', 'div', 'pm', 'angle', 'leq', 'geq', 'neq', 'approx', 'dots', 'cdots', 'ldots', 'cdot', 'quad', 'qquad', 'infty', 'partial', 'degree', 'wedge', 'vee', 'cup', 'cap', 'int', 'sum', 'prod', 'lim', 'inf', 'sup', 'max', 'min', 'mod', 'triangle', 'square', 'circ', 'perp', 'parallel', 'measuredangle', 'nabla', 'forall', 'exists', 'neg', 'lor', 'land', 'in', 'notin', 'subset', 'supset', 'subseteq', 'supseteq', 'left', 'right', 'begin', 'end'];
  
  // Fix spaced commands like \ sin -> \sin or \ \theta -> \theta
  sanitized = sanitized.replace(/\\+\s+(?=[a-zA-Z])/g, '\\');
  sanitized = sanitized.replace(/\\\s+(sin|cos|tan|log|ln|sqrt|frac|sum|int|lim|theta|alpha|beta|gamma|delta|pi|phi|omega|sigma|lambda|dots|circ|begin|end|left|right)/g, (m, p1) => '\\' + p1);

  // Fix missing backslash for common environments and delimiters
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])(begin|end|left|right)\b(?![a-zA-Z0-9])/g, '\\$1');
  
  // Deduplicate and fix nested AI math artifacts like \left\left( or \left \left (
  // Use recursive replacement to handle triple or quadruple ones
  let prevSanitized;
  do {
    prevSanitized = sanitized;
    // 1. Double backslash commands
    sanitized = sanitized.replace(/(\\left)\s*\\left/g, '\\left');
    sanitized = sanitized.replace(/(\\right)\s*\\right/g, '\\right');
    
    // 2. Double brackets with \left
    sanitized = sanitized.replace(/\\left\s*\(\s*\\left\s*\(/g, '\\left(');
    sanitized = sanitized.replace(/\\right\s*\)\s*\\right\s*\)/g, '\\right)');
    
    // 3. Mixed variants
    sanitized = sanitized.replace(/(\\left\s*[({[])\s*\\left/g, '$1');
    sanitized = sanitized.replace(/(\\right\s*[)}\]])\s*\\right/g, '$1');
  } while (sanitized !== prevSanitized);
  
  // Fix double delimiters like (( x )) -> ( x )
  // Use a heuristic: if we see (( and )) with no logic between them, simplify
  sanitized = sanitized.replace(/(\\left\s*\(|(?<!\\)\()\s*(\\left\s*\(|(?<!\\)\()/g, '\\left(');
  sanitized = sanitized.replace(/(\\right\s*\)|(?<!\\)\))\s*(\\right\s*\)|(?<!\\)\))/g, '\\right)');
  
  // Fix SHORT commands like \frac12 -> \frac{1}{2}
  sanitized = sanitized.replace(/\\frac(\d)(\d)/g, '\\frac{$1}{$2}');
  sanitized = sanitized.replace(/\\frac(\d+)/g, (m, p1) => p1.length === 2 ? `\\frac{${p1[0]}}{${p1[1]}}` : m);
  sanitized = sanitized.replace(/\\sqrt(\d+)/g, (m, p1) => p1.length === 1 ? `\\sqrt{${p1}}` : m);
  
  sanitized = sanitized.replace(/\\(sin|cos|tan|log|ln|sqrt|frac|theta|alpha|beta|pi|dots|circ|deg)\s*([\^_{}])/g, '\\$1$2');
  sanitized = sanitized.replace(/([\^_])\s*\{([^}]*)\}/g, '$1{$2}');
  sanitized = sanitized.replace(/([\^_])\s*(\d+)/g, '$1{$2}');

  // 4. Aggressive Math detection for naked expressions
  const environments = 'align\\*?|alignat\\*?|alignedat|cases|matrix|pmatrix|vmatrix|bmatrix|Bmatrix|Vmatrix|gather\\*?|multline\\*?|split|aligned|smallmatrix|array';
  // Robust label prefix: match anything alphanumeric/math symbols followed by relation/colon
  const labelPrefix = '([\\w\\s\\(\\)\\{\\}\\[\\]=<>+\\-\\*/\\.,_\\^\\!\\$]*?\\s*[=<>\\!\\:]\\s*)?';
  const envRegex = new RegExp(`(?<![\\\\\\w])(\\$*\\s*)${labelPrefix}(\\\\begin\\{(${environments})\\}[\\s\\S]*?\\\\end\\{\\3\\})(\\s*\\$*)`, 'g');
  
  sanitized = sanitized.replace(envRegex, (match, pre, label, env, envName, post) => {
    // Strip all $ from AI artifacts in label and env
    const cleanLabel = (label || '').replace(/\$/g, '').trim();
    const cleanEnv = env.replace(/\$/g, '').trim();
    const combined = (cleanLabel + ' ' + cleanEnv).trim();
    
    // Convert to inline math to respect sentence flow, matrix will still handle its own height
    return `$${combined}$`;
  });

  // B. Specific wrapper for \left...\right blocks if they are naked
  sanitized = sanitized.replace(/(?<![$\\\w{])(\\left\b[\s\S]*?\\right\b[.\(\)\[\]\{\}\/\\|])(?![$\w}])/g, '$$1$');

  // B. Robust "Math Island" Detection
  const braceLevel1 = /\{(?:[^{}]*)\}/.source;
  const braceLevel2 = /(?:\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\})/.source;
  const braceLevel3 = /(?:\{[^{}]*(?:\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}[^{}]*)*\})/.source;

  // This identifies blocks of math-heavy text and wraps them in dollars if not already wrapped.
  // It stops at any Bengali character or significant plain text word.
  // We explicitly include common command seeds to trigger detection
  const commonMathSeeds = 'left|right|frac|sqrt|sin|cos|tan|log|ln|sum|int|prod|lim|dots|cdots|ldots|circ|theta|alpha|beta|gamma|delta|pi|phi|omega|sigma|lambda';
  
  // A pattern that matches math-like characters (digits, LaTeX commands, symbols) 
  // but excludes Bengali and common sentence words.
  const mathChars = `[a-zA-Z0-9\\(\\)\\[\\]\\^_^{}\\s+*/\\\\&\\|!<>=-±×÷√∞∫≈≠≤≥πθλμϕωαβγδεζηικξρστυχψ]`;
  const commandPattern = `(?:\\\\[a-zA-Z0-9]+(?:\\s*${braceLevel3}|\\s*\\[[^\\]]*\\]|\\s+[a-zA-Z0-9]+|[\\^_]${braceLevel3}|[\\^_][a-zA-Z0-9]|\\s*\\([^)]*\\))*|\\\\[,;!:#$%&_{}])`;
  const mathCharPattern = `(?:${commandPattern}|${mathChars}|[,.;:?])`;
  
  // Find a "seed" (a backslash command or a variable followed by operator) and expand it.
  const islandRegex = new RegExp(`(?<![$\\\\\\w{])((?:${mathCharPattern}*?(?:\\\\[a-zA-Z]+|[\\^_{}=<>|&±×÷√∞∫≈≠≤≥])${mathCharPattern}*?))(?=(?:[\\u0980-\\u09FF\\u0964\\u0965]|\\n\\n|\\r\\n\\r\\n|$))`, 'g');
  
  sanitized = sanitized.replace(islandRegex, (match) => {
    if (match.includes('$') || match.includes('\\begin')) return match;
    const trimmed = match.trim();
    if (trimmed.length < 2) return match;
    if (trimmed.match(/[\u0980-\u09FF\u0964\u0965]/)) return match;
    
    // Safety check: skip if it contains common words that indicate it's actually a sentence
    const words = trimmed.split(/\s+/);
    const stopWords = ['and', 'for', 'the', 'was', 'with', 'that', 'this', 'from', 'each', 'does', 'each', 'were', 'which', 'their', 'there', 'some', 'any', 'all'];
    // If it contains a backslash command, we are much more confident it's math
    const hasBackslashCommand = trimmed.includes('\\');
    if (words.some(w => stopWords.includes(w.toLowerCase())) && !hasBackslashCommand) return match;
    
    // Check for "too many" long words if NO backslash is present
    const longWords = words.filter(w => w.length > 5 && /^[a-zA-Z]+$/.test(w));
    if (longWords.length > 2 && !hasBackslashCommand) return match;

    // Check for unbalanced braces
    const openBraces = (trimmed.match(/\{/g) || []).length;
    const closeBraces = (trimmed.match(/\}/g) || []).length;
    if (openBraces !== closeBraces) return match;

    const isMultiLine = (trimmed.match(/\n/g) || []).length > 0 || trimmed.length > 100 || (trimmed.includes('\\\\') && !trimmed.includes('matrix'));
    return isMultiLine ? ` $$ ${trimmed} $$ ` : `$${trimmed}$`;
  });

  // C. Combinations/Permutations (Standard notation: nCr or nPr)
  // We use a more careful match to avoid catching Bengali text
  sanitized = sanitized.replace(/(?<=[ \u0980-\u09FF]|^|\(|\$)(\d+|n|N)\s*([CP])\s*(\d+|r|R)(?=[ \u0980-\u09FF]|$|\)|\$)/g, (match, p1, p2, p3) => ' ${}^{' + p1 + '}' + p2 + '_{' + p3 + '}$ ');
  sanitized = sanitized.replace(/\b([CP])\s*\(\s*(\d+|[nN]|[a-zA-Z])\s*,\s*(\d+|[rR]|[a-zA-Z])\s*\)/g, (match, p1, p2, p3) => ' ${}^{' + p2 + '}' + p1 + '_{' + p3 + '}$ ');

  // Removed E and F as they are too brittle and cause corruption in complex expressions

  // 4G. Heal fragmented LaTeX - join blocks that got separate wraps but should be one
  // Fixes $ x $ $ = 5 $ -> $ x = 5 $
  sanitized = sanitized.replace(/\$\s+([=<>+\-*/])\s+\$/g, ' $1 ');
  
  // Fixes "$A=$ $$...$$" -> "$$A=...$$"
  // Handles mixed inline and display blocks that were likely meant to be one item
  sanitized = sanitized.replace(/\$\s*([a-zA-Z0-9\(\)\s]*\s*[=<>]\s*)\$\s+\$\$/g, (m, p1) => '$$' + p1 + ' ');
  sanitized = sanitized.replace(/\$\$\s+([a-zA-Z0-9\(\)\s]*\s*[=<>]\s*)\$\s+\$\$/g, (m, p1) => '$$' + p1 + ' ');
  
  // Join adjacent math of any variety
  sanitized = sanitized.replace(/\$\s*\$/g, ' ');
  sanitized = sanitized.replace(/\$\$\s*\$\$/g, ' ');
  sanitized = sanitized.replace(/\$\s*\$\$/g, ' ');
  sanitized = sanitized.replace(/\$\$\s*\$/g, ' ');
  
  // 5. Global Block Fixup (Fix missing backslashes inside identified blocks)
  // This handles both $...$ and $$...$$
  sanitized = sanitized.replace(/(\$\$?)([\s\S]*?)\1/g, (match, prefix, inner) => {
    let fixed = inner;
    
    // Ensure all known symbols have backslashes
    mathSymbols.forEach(sym => {
      // Match symbol if not already backslashed and not part of another word
      // Handle cases like "frac12" by not requiring a trailing word boundary if a digit follows
      const regex = new RegExp(`(?<![\\\\a-zA-Z])${sym}(?![a-zA-Z])`, 'g');
      fixed = fixed.replace(regex, (match, offset) => {
        // Don't add backslash if it's an environment name inside \begin{...} or \end{...}
        const prev = fixed.substring(0, offset);
        if (prev.match(/\\(begin|end)\{$/)) return match;
        // Use double backslash to be safe
        return '\\' + sym;
      });
    });

    // Re-apply short command fix inside blocks after adding missing backslashes
    fixed = fixed.replace(/\\frac(\d)(\d)/g, '\\frac{$1}{$2}');
    fixed = fixed.replace(/\\sqrt(\d)/g, '\\sqrt{$1}');

    // Handle operator conversion
    fixed = fixed.replace(/\s*\*\s*/g, ' \\times ');
    fixed = fixed.replace(/ \/ (?![\d]) /g, ' \\div ');
    
    // Fix fraction slash to \frac if it's simple numbers or isolated variables
    // Avoid splitting common commands like \pi/2 or \theta/4
    fixed = fixed.replace(/(?<![a-zA-Z\\])(\d+|[a-zA-Z])\/(\d+|[a-zA-Z\(\)])(?![a-zA-Z])/g, (m, p1, p2) => {
      return `\\frac{${p1}}{${p2}}`;
    });

    // Fix log base notation: log 2 -> \log_{2}, log10 -> \log_{10}
    fixed = fixed.replace(/\\log\s+(\d+)/g, '\\log_{$1}');
    fixed = fixed.replace(/(?<!\\)log(\d+)/g, '\\log_{$1}');
    fixed = fixed.replace(/(?<!\\)log\s+(\d+)/g, '\\log_{$1}');

    // AUTO-SIZING BRACKETS: Convert ( ... \frac ... ) to \left( ... \frac ... \right)
    const resizeBrackets = (s: string) => {
      let current = s;
      
      // If the block contains "tall" math, we should ensure brackets are resized
      if (current.match(/\\frac|\^|_|\\sqrt|\\sum|\\int|\\prod|\\lim|\\log/)) {
        // 1. Entire block check (if the whole thing is inside brackets)
        const trimmed = current.trim();
        if (trimmed.startsWith('(') && trimmed.endsWith(')')) {
          current = `\\left( ${trimmed.slice(1, -1)} \\right)`;
        } else if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
          current = `\\left[ ${trimmed.slice(1, -1)} \\right]`;
        } else if (trimmed.startsWith('\\{') && trimmed.endsWith('\\}')) {
          current = `\\left\\{ ${trimmed.slice(2, -2)} \\right\\}`;
        }
        
        // 2. Focused internal patterns (catch fragments like "(1/2)")
        // We use a safer regex for non-nested brackets first
        current = current.replace(/(?<!\\)\(([^()]*?(\\frac|\^|_|\\sqrt|\\sum|\\int|\\log)[^()]*?)(?<!\\)\)/g, '\\left($1\\right)');
        current = current.replace(/(?<!\\)\[([^[\]]*?(\\frac|\^|_|\\sqrt|\\sum|\\int|\\log)[^[\]]*?)(?<!\\)\]/g, '\\left[$1\\right]');
        current = current.replace(/(?<!\\)\\{([^{}]*?(\\frac|\^|_|\\sqrt|\\sum|\\int|\\log)[^{}]*?)(?<!\\)\\}/g, '\\left\\{$1\\right\\}');
      }
      
      return current;
    };

    fixed = resizeBrackets(fixed);
    
    return `${prefix}${fixed.trim()}${prefix}`;
  });

  // 6. Bengali Digit Harmonization inside math
  sanitized = sanitized.replace(/(\$\$?)([\s\S]*?)\1/g, (match, prefix, inner) => {
    const bengaliDigits = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
    let englishInner = inner.split('').map(char => {
      const idx = bengaliDigits.indexOf(char);
      return idx !== -1 ? idx.toString() : char;
    }).join('');
    return `${prefix}${englishInner}${prefix}`;
  });

  // 7. Deduplicate and Join Adjacent Delimiters
  // Join adjacent math blocks: $Math1$ $Math2$ -> $Math1 Math2$
  sanitized = sanitized.replace(/\$\s*\$/g, ' ');
  sanitized = sanitized.replace(/\$\$\s*\$\$/g, ' ');
  
  // Clean up any triple dollars or broken delimiters
  sanitized = sanitized.replace(/\$\$\$/g, '$$');
  
  // Final spacing: ensures math is separated from Bengali characters to prevent squashing
  // Use a more robust regex to catch all cases including end of string/line
  sanitized = sanitized.replace(/([\u0980-\u09FF\u0964\u0965])(\$\$?)/g, '$1 $2');
  sanitized = sanitized.replace(/(\$\$?)([\u0980-\u09FF\u0964\u0965])/g, '$1 $2');
  
  // Ensure that numbers, variables and common punctuation stuck to Bengali characters have a space
  sanitized = sanitized.replace(/([a-zA-Z0-9\)])([\u0980-\u09FF\u0964\u0965]+)/g, '$1 $2');
  sanitized = sanitized.replace(/([\u0980-\u09FF\u0964\u0965]+)([a-zA-Z0-9\(])/g, '$1 $2');
  sanitized = sanitized.replace(/([\u0980-\u09FF\u0964\u0965])(\$)/g, '$1 $2');
  sanitized = sanitized.replace(/(\$)([\u0980-\u09FF\u0964\u0965])/g, '$1 $2');

  // Fix accidental triple/quadruple dollars
  sanitized = sanitized.replace(/\${3,}/g, '$$$$');

  // 8. FINAL HEAL: Join adjacent math blocks $A$ $B$ -> $A B$
  // This handles cases where our island detection might have been split by something it didn't recognize correctly
  sanitized = sanitized.replace(/\$\s+\$/g, ' ');
  sanitized = sanitized.replace(/\$\$\s+\$\$/g, ' ');

  // Fix corrupted commands like 'rac', 'ext', or missing 'i' in '\pi' at the final stage
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])rac(\d)(\d)/g, '\\frac{$1}{$2}');
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])rac\{/g, '\\frac{');
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])ext\{/g, '\\text{');
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])ext(?=[\u0980-\u09FF])/g, '\\text'); // Case where brace might be missing
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])heta(?![a-zA-Z0-9])/g, '\\theta');
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])imes(?![a-zA-Z0-9])/g, '\\times');
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])ight(?![a-zA-Z0-9])/g, '\\right');
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])eft(?![a-zA-Z0-9])/g, '\\left');
  sanitized = sanitized.replace(/\\p(\s+)?i(?![a-zA-Z])/g, '\\pi');
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])abla(?![a-zA-Z0-9])/g, '\\nabla');
  sanitized = sanitized.replace(/(?<![\\a-zA-Z])qrt\{/g, '\\sqrt{');

  return sanitized;
};

/**
 * Deeply sanitizes math strings for KaTeX.
 */
export const sanitizeMathForKatex = (math: string): string => {
  let cleaned = math.trim();
  
  // Remove outer $ if present
  if (cleaned.startsWith('$') && cleaned.endsWith('$')) {
    cleaned = cleaned.slice(1, -1);
  }

  // Remove inner dollars that AI often inserts inside complex expressions (e.g. \begin{matrix}$x$ ... \end{matrix})
  // We do this AFTER removing outer delimiters to avoid stripping the delimiters themselves
  cleaned = cleaned.replace(/(?<!\\)\$/g, '');
  
  // Remove common AI artifacts like unbalanced braces
  let openBraces = (cleaned.match(/\{/g) || []).length;
  let closeBraces = (cleaned.match(/\}/g) || []).length;
  
  // 1. Remove extra closing braces
  while (closeBraces > openBraces && cleaned.includes('}')) {
    if (cleaned.endsWith('}')) {
      cleaned = cleaned.slice(0, -1);
    } else if (cleaned.startsWith('}')) {
      cleaned = cleaned.slice(1);
    } else {
      const lastIdx = cleaned.lastIndexOf('}');
      cleaned = cleaned.substring(0, lastIdx) + cleaned.substring(lastIdx + 1);
    }
    closeBraces--;
  }
  
  // 2. Add missing closing braces at the end
  while (openBraces > closeBraces) {
    // If it looks like a missing brace for \frac{...}{ or similar
    cleaned += '}';
    closeBraces++;
  }

  // 3. Add missing closing parentheses
  let openParens = (cleaned.match(/\(/g) || []).length;
  let closeParens = (cleaned.match(/\)/g) || []).length;
  while (openParens > closeParens) {
    cleaned += ')';
    closeParens++;
  }
  
  // 3.5. Fix "naked" math in text blocks if they are simple words but inside KaTeX
  // We use a known list of commands to distinguish them from English words
  const KNOWN_COMMANDS = new Set([
    'frac','sqrt','text','mathrm','mathbf','mathit','begin','end',
    'left','right','over','under','sum','int','prod','lim','sin',
    'cos','tan','log','ln','alpha','beta','gamma','delta','theta',
    'sigma','lambda','omega','phi','pi','infty','partial','nabla',
    'forall','exists','cdot','cdots','ldots','dots','quad','qquad',
    'times','div','pm','leq','geq','neq','approx','circ','perp',
    'parallel','subset','supset','cup','cap','wedge','vee','neg',
    'array','matrix','pmatrix','bmatrix','vmatrix','cases','align',
    'exp','min','max','sup','inf','arg','ker','dim','det','deg'
  ]);

  cleaned = cleaned.replace(
    /(?<!\\|\{)\b([a-zA-Z]{4,})\b(?!\})/g,
    (match) => KNOWN_COMMANDS.has(match.toLowerCase()) ? match : `\\text{${match}}`
  );
  
  // Convert Bengali digits to English for math
  const bengaliDigits = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
  cleaned = cleaned.split('').map(char => {
    const idx = bengaliDigits.indexOf(char);
    return idx !== -1 ? idx.toString() : char;
  }).join('');

  // 3. Fix missing backslashes for common functions
  cleaned = cleaned.replace(/(?<!\\)\b(sin|cos|tan|log|ln|sqrt|frac)\b/g, (m) => '\\' + m);

  // Final check for "naked" frac12 etc if missing backslash 
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])frac(\d)(\d)/g, '\\frac{$1}{$2}');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])frac\{/g, '\\frac{');
  
  // Fix log base notation: \log 10 -> \log_{10}
  cleaned = cleaned.replace(/\\log\s+(\d+)/g, '\\log_{$1}');
  cleaned = cleaned.replace(/(?<!\\)log(\d+)/g, '\\log_{$1}');
  cleaned = cleaned.replace(/(?<!\\)log\s+(\d+)/g, '\\log_{$1}');
  
  // Fix specifically corrupted 'rac' and 'ext' artifacts
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])rac(\d)(\d)/g, '\\frac{$1}{$2}');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])rac\{/g, '\\frac{');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])ext\{/g, '\\text{');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])ext(?=[\u0980-\u09FF])/g, '\\text');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])heta(?![a-zA-Z0-9])/g, '\\theta');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])imes(?![a-zA-Z0-9])/g, '\\times');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])ight(?![a-zA-Z0-9])/g, '\\right');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])eft(?![a-zA-Z0-9])/g, '\\left');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])abla(?![a-zA-Z0-9])/g, '\\nabla');
  cleaned = cleaned.replace(/(?<![\\a-zA-Z])qrt\{/g, '\\sqrt{');
  
  // Fix specifically corrupted '\p i' -> '\pi'
  cleaned = cleaned.replace(/\\p\s+i/g, '\\pi');
  cleaned = cleaned.replace(/\\p(?![a-zA-Z])(?!i)/g, '\\pi');

  // 4. Deduplicate AI artifacts like \left\left( or \left \left (
  let lastCleaned;
  do {
    lastCleaned = cleaned;
    cleaned = cleaned.replace(/(\\left)\s*\\left/g, '\\left');
    cleaned = cleaned.replace(/(\\right)\s*\\right/g, '\\right');
    cleaned = cleaned.replace(/(\\left\s*[({[])\s*\\left/g, '$1');
    cleaned = cleaned.replace(/(\\right\s*[)}\]])\s*\\right/g, '$1');
    cleaned = cleaned.replace(/\\left\s*\(\s*\\left\s*\(/g, '\\left(');
    cleaned = cleaned.replace(/\\right\s*\)\s*\\right\s*\)/g, '\\right)');
  } while (cleaned !== lastCleaned);

  // Common KaTeX replacements
  cleaned = cleaned
    .replace(/(\d+)°/g, '$1^\\circ')
    .replace(/(?<!\^)\\deg\b/g, '^\\circ')
    .replace(/(?<!\^)\\degree\b/g, '^\\circ')
    .replace(/(?<!\^)\\circ\b/g, '^\\circ');
    
  return cleaned;
};
