/**
 * Utility functions for math normalization and LaTeX sanitization.
 */

/**
 * Fixes common malformed LaTeX generated by AI models.
 */
export const normalizeLatex = (text: string): string => {
  if (!text) return '';

  let sanitized = text;

  // 1. Basic cleaning
  sanitized = sanitized
    .replace(/```[a-z]*\n?/g, '') // Strip markdown code blocks
    .replace(/```/g, '')
    .replace(/\u000c/g, '\\\\f')  
    .replace(/\u0008/g, '\\\\b')  
    .replace(/\r\n/g, ' ')
    .replace(/\n\r/g, ' ')
    .replace(/\n/g, ' ');

  // 2. Fix malformed fraction patterns like frac35 -> \frac{3}{5}
  // Matches 'frac' followed by two digits
  sanitized = sanitized.replace(/frac(\d)(\d)/g, '\\frac{$1}{$2}');
  // Matches 'frac' followed by a digit and a group
  sanitized = sanitized.replace(/frac(\d)\{([^{}]+)\}/g, '\\frac{$1}{$2}');
  // Matches 'frac' followed by a group and a digit
  sanitized = sanitized.replace(/frac\{([^{}]+)\}(\d)/g, '\\frac{$1}{$2}');
  
  // 3. Fix missing backslashes for common functions and symbols
  const funcs = ['sin', 'cos', 'tan', 'cot', 'sec', 'csc', 'log', 'ln', 'sqrt', 'frac', 'theta', 'alpha', 'beta', 'gamma', 'delta', 'pi', 'phi', 'deg', 'circ', 'omega', 'sigma', 'lambda', 'times', 'div', 'pm', 'angle', 'triangle', 'approx', 'neq', 'leq', 'geq', 'dots', 'cdots', 'ldots', 'cdot', 'quad', 'qquad', 'infty', 'partial', 'degree'];
  
  // 4. Aggressively fix exponents for KaTeX: x^2 -> x^{2}
  // We target digits and single letters to avoid breaking commands
  sanitized = sanitized.replace(/([a-zA-Z0-9)\]])\^([0-9])/g, '$1^{$2}');
  sanitized = sanitized.replace(/([a-zA-Z0-9)\]])\^([a-zA-Z])(?![a-zA-Z0-9])/g, '$1^{$2}');
  
  // 5. Fix trig functions with parentheses but no spacing/brackets
  sanitized = sanitized.replace(/\\(sin|cos|tan)\(([^)]+)\)/g, (match, func, arg) => {
    let fixedArg = arg;
    funcs.forEach(f => {
      const r = new RegExp(`(?<!\\\\)\\b${f}\\b`, 'g');
      fixedArg = fixedArg.replace(r, `\\${f}`);
    });
    return `\\${func}(${fixedArg})`;
  });

  // 6. Fix sqrt: sqrt1-x -> \sqrt{1-x}
  sanitized = sanitized.replace(/\\sqrt\s*([a-zA-Z0-9.\-+*/]+)(?!\s*[{[])/g, '\\sqrt{$1}');

  // 6b. Fix Combinations and Permutations like C(9, 3) or 9C3
  sanitized = sanitized.replace(/\bC\s*\(\s*(\d+|[nN]|[a-zA-Z])\s*,\s*(\d+|[rR]|[a-zA-Z])\s*\)/g, '{}^{$1}C_{$2}');
  sanitized = sanitized.replace(/\bP\s*\(\s*(\d+|[nN]|[a-zA-Z])\s*,\s*(\d+|[rR]|[a-zA-Z])\s*\)/g, '{}^{$1}P_{$2}');
  sanitized = sanitized.replace(/(\d+)\s*C\s*(\d+)/g, '{}^{$1}C_{$2}');
  sanitized = sanitized.replace(/(\d+)\s*P\s*(\d+)/g, '{}^{$1}P_{$2}');

  // 6c. Fix double carets and other common AI mistakes
  sanitized = sanitized.replace(/\^{2,}/g, '^');
  sanitized = sanitized.replace(/_{2,}/g, '_');

  // 7. Auto-wrap "Naked Math" segments (segments that look like math but have no delimiters)
  // We split by existing delimiters first to avoid double wrapping
  const existingDelimiters = /(\$\$.*?\$\$|\$.*?\$|\\\(.*?\\\)|\\\[.*?\\\])/g;
  let parts = sanitized.split(existingDelimiters);
  
  const autoWrapPatterns = [
    /\\(?:frac|sqrt|sin|cos|tan|theta|pi|alpha|beta|delta|gamma|phi|times|div|pm|angle|leq|geq|neq|approx|dots|cdots|ldots|cdot|quad|qquad|infty|partial|degree)/, // Contains backslash command
    /[a-zA-Z0-9]+\^{[^}]+}/, // Contains explicit exponent x^{...}
    /[a-zA-Z0-9]+\^[a-zA-Z0-9]+/, // Contains simple exponent x^2
    /[a-zA-Z0-9]+_{[^}]+}/, // Contains explicit subscript x_{...}
    /[a-zA-Z0-9]+_[a-zA-Z0-9]+/, // Contains simple subscript x_1
    /[a-z]\(x\)\s*[=><]/, // looks like f(x) = ...
    /[a-z]'\(.*?\)/, // looks like f'(x)
    /[0-9xX]\s*[*+\-/=]\s*[0-9xX]/, // basic arithmetic 2*2 or x+1
    /[0-9xX]\s*[=><]\s*[0-9xX]/, // equality x=1
    /[CP]\s*\(\d+,\s*\d+\)/, // Combination/Permutation C(9,3)
    /\d+[CP]\d+/, // 9C3 or 9P3
  ];

  sanitized = parts.map(part => {
    // If it's already wrapped, don't touch it
    if (part.match(/^(\$\$.*?\$\$|\$.*?\$|\\\(.*?\\\)|\\\[.*?\\\])$/)) return part;
    
    // Improved logic: Instead of wrapping the whole segment which might contain sentences,
    // let's try to wrap specific mathematical phrases if the segment looks like math.
    if (autoWrapPatterns.some(pattern => part.match(pattern))) {
      const bengaliCount = (part.match(/[\u0980-\u09FF]/g) || []).length;
      
      // If there's no Bengali at all, wrap the whole thing if it's not too long
      // This is helpful for explanations like "f'(x) = 2*2 = 4"
      if (bengaliCount === 0 && part.trim().length > 0 && part.trim().length < 200) {
        return ` $${part.trim()}$ `;
      }
      
      // If there is Bengali, we only wrap if it's mostly mathematical
      if (bengaliCount < 5 && part.trim().length < 120) {
        return ` $${part.trim()}$ `;
      }
    }
    return part;
  }).join('');

  // 8. Final pass: ensure common symbols have backslashes if inside $...$ 
  // AND convert * to \times for cleaner rendering
  sanitized = sanitized.replace(/\$(.*?)\$/g, (match, inner) => {
    let fixedInner = inner;
    
    // Convert * to \times (but not if it's inside a command or part of something else)
    // Simple approach: replace space-surrounded * or digit-surrounded *
    fixedInner = fixedInner.replace(/(\d)\s*\*\s*(\d)/g, '$1 \\times $2');
    fixedInner = fixedInner.replace(/([a-zA-Z0-9])\s*\*\s*([a-zA-Z0-9])/g, '$1 \\times $2');

    funcs.forEach(f => {
      const r = new RegExp(`(?<!\\\\)\\b${f}\\b`, 'g');
      fixedInner = fixedInner.replace(r, `\\${f}`);
    });
    return `$${fixedInner}$`;
  });

  return sanitized;
};

/**
 * Deeply sanitizes math strings for KaTeX.
 */
export const sanitizeMathForKatex = (math: string): string => {
  let cleaned = math.trim();
  
  // Remove outer $ if present
  if (cleaned.startsWith('$') && cleaned.endsWith('$')) {
    cleaned = cleaned.slice(1, -1);
  }
  
  // Convert Bengali digits to English for math
  const bengaliDigits = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
  cleaned = cleaned.split('').map(char => {
    const idx = bengaliDigits.indexOf(char);
    return idx !== -1 ? idx.toString() : char;
  }).join('');

  // Common KaTeX replacements
  cleaned = cleaned
    .replace(/(\d+)°/g, '$1^\\circ')
    .replace(/(?<!\^)\\deg\b/g, '^\\circ')
    .replace(/(?<!\^)\\degree\b/g, '^\\circ')
    .replace(/(?<!\^)\\circ\b/g, '^\\circ');
    
  return cleaned;
};
