/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Gamepad2, 
  Brain, 
  BrainCircuit,
  Flame,
  Trophy, 
  ShoppingBag, 
  ChevronRight,
  ArrowRight,
  CheckCircle,
  X,
  Zap,
  Target,
  LineChart,
  Award,
  Crown,
  Languages,
  Sun,
  Moon,
  Key
} from 'lucide-react';
import { translations } from '../lib/translations';
import AppTooltip from './Tooltip';

import Logo from './Logo';

interface TutorialProps {
  onComplete: () => void;
  language: 'en' | 'bn';
  onLanguageToggle: () => void;
  isDark: boolean;
  onThemeToggle: () => void;
}

export default function Tutorial({ onComplete, language, onLanguageToggle, isDark, onThemeToggle }: TutorialProps) {
  const [step, setStep] = useState(0);
  const t = translations[language];

  const steps = [
    {
      title: language === 'en' ? 'Welcome to Math Mind!' : 'ম্যাথ মাইন্ডে স্বাগতম!',
      desc: language === 'en' 
        ? 'The ultimate interactive math quiz playground. Boost your logic while having fun!' 
        : 'সেরা ইন্টারঅ্যাক্টিভ ম্যাথ কুইজ প্ল্যাটফর্ম। মজার মাধ্যমে আপনার যুক্তিশক্তি বাড়ান!',
      icon: <Logo size={120} />,
      color: 'bg-primary/20',
      tip: language === 'en' ? 'Pro Tip: Tap the logo anytime to see your stats!' : 'টিপ: আপনার স্ট্যাটাস দেখতে যেকোনো সময় লোগোতে ট্যাপ করুন!',
      customUI: (
        <div className="flex flex-col gap-4 mt-4 w-full max-w-[280px]">
          <div className="flex flex-col gap-2 p-3 bg-black/5 dark:bg-white/5 rounded-2xl border border-white/5">
             <div className="flex items-center gap-2 mb-1">
               <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center text-primary">
                 <Languages size={14} />
               </div>
               <span className="text-[10px] font-black uppercase tracking-wider opacity-60">
                 {language === 'en' ? 'Choose Language' : 'ভাষা নির্বাচন করুন'}
               </span>
             </div>
             <div className="flex gap-2">
               <button 
                 onClick={() => language !== 'en' && onLanguageToggle()}
                 className={`flex-1 px-3 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${
                   language === 'en' ? 'bg-primary text-white shadow-lg shadow-primary/20' : 'bg-black/5 dark:bg-white/5 text-muted hover:bg-black/10'
                 }`}
               >
                 🇺🇸 English
               </button>
               <button 
                 onClick={() => language !== 'bn' && onLanguageToggle()}
                 className={`flex-1 px-3 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${
                   language === 'bn' ? 'bg-primary text-white shadow-lg shadow-primary/20' : 'bg-black/5 dark:bg-white/5 text-muted hover:bg-black/10'
                 }`}
               >
                 🇧🇩 বাংলা
               </button>
             </div>
          </div>

          <div className="flex items-center justify-between p-3 bg-black/5 dark:bg-white/5 rounded-2xl border border-white/5">
             <div className="flex items-center gap-2">
               <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-primary">
                 {isDark ? <Moon size={16} /> : <Sun size={16} />}
               </div>
               <span className="text-[11px] font-black uppercase tracking-wider opacity-60">
                 {language === 'en' ? 'Theme' : 'থিম'}
               </span>
             </div>
             <button 
                onClick={onThemeToggle}
                className="w-14 h-8 rounded-full bg-black/10 dark:bg-white/10 relative p-1 transition-colors flex items-center"
             >
                <div className="absolute inset-0 flex items-center justify-between px-2.5 text-muted/30">
                  <Sun size={12} />
                  <Moon size={12} />
                </div>
                <motion.div 
                  animate={{ x: isDark ? 24 : 0 }}
                  className="w-6 h-6 rounded-full bg-primary shadow-lg z-10 flex items-center justify-center text-white"
                >
                   {isDark ? <Moon size={12} /> : <Sun size={12} />}
                </motion.div>
             </button>
          </div>
        </div>
      )
    },
    {
      title: language === 'en' ? 'AI Powered Quizzes' : 'AI চালিত কুইজ',
      desc: language === 'en' 
        ? 'Real-time questions generated by Gemini AI. No two quizzes are ever the same!' 
        : 'জেমিনি এআই দিয়ে রিয়েল-টাইমে তৈরি প্রশ্ন। কোনো কুইজই একে অপরের মতো হবে না!',
      icon: <BrainCircuit className="text-indigo-500" size={80} />,
      color: 'bg-indigo-500/10',
      tip: language === 'en' ? 'Choose "Hard" mode for advanced math challenges.' : 'উন্নত গণিত চ্যালেঞ্জের জন্য "হার্ড" মোড বেছে নিন।'
    },
    {
      title: language === 'en' ? 'Daily Flame Streak' : 'ডেইলি ফ্লেম স্ট্রিক',
      desc: language === 'en' 
        ? 'Play daily to build your streak. Reach higher tiers and earn bonus points!' 
        : 'আপনার স্ট্রিক বাড়াতে প্রতিদিন খেলুন। উচ্চ স্তরে পৌঁছান এবং বোনাস পয়েন্ট জিতুন!',
      icon: <Flame className="text-rose-500" size={80} />,
      color: 'bg-rose-500/10',
      tip: language === 'en' ? 'A 7-day streak gives you a "Legendary" badge.' : '৭ দিনের স্ট্রিক আপনাকে একটি "লেজেন্ডারি" ব্যাজ দেবে।'
    },
    {
      title: language === 'en' ? 'Achievements & Titles' : 'অ্যাচিভমেন্ট এবং টাইটেল',
      desc: language === 'en' 
        ? 'Unlock master titles like "Math Master" or "Speed Demon" by hitting milestones.' 
        : 'মাইলফলক স্পর্শ করে "ম্যাথ মাস্টার" বা "স্পিড ডিমন" এর মতো টাইটেল আনলক করুন!',
      icon: <Award className="text-amber-500" size={80} />,
      color: 'bg-amber-500/10',
      tip: language === 'en' ? 'Check the Achievements tab for your next goal.' : 'আপনার পরবর্তী লক্ষ্য জানতে অ্যাচিভমেন্ট ট্যাব দেখুন।'
    },
    {
      title: language === 'en' ? 'The Math Store' : 'ম্যাথ স্টোর',
      desc: language === 'en' 
        ? 'Use your earned points to unlock Premium Themes and Custom Avatar styles.' 
        : 'আপনার অর্জিত পয়েন্ট ব্যবহার করে প্রিমিয়াম থিম এবং কাস্টম অবতার স্টাইল আনলক করুন!',
      icon: <ShoppingBag className="text-purple-500" size={80} />,
      color: 'bg-purple-500/10',
      tip: language === 'en' ? 'The "Cyberpunk" theme is our most popular look!' : '"সাইবারপাঙ্ক" থিমটি আমাদের সবচেয়ে জনপ্রিয় লুক!'
    },
    {
      title: language === 'en' ? 'Global Leaderboard' : 'গ্লোবাল লিডারবোর্ড',
      desc: language === 'en' 
        ? 'Compete against rivals and climb to the top of the World mathematician ranks!' 
        : 'প্রতিদ্বন্দ্বীদের সাথে প্রতিযোগিতা করুন এবং বিশ্ব গণিতবিদদের তালিকায় শীর্ষে উঠুন!',
      icon: <Crown className="text-yellow-500" size={80} />,
      color: 'bg-yellow-500/10',
      tip: language === 'en' ? 'Can you beat our current top-ranked player?' : 'আপনি কি আমাদের বর্তমান সেরা খেলোয়াড়কে হারাতে পারবেন?'
    },
    {
      title: language === 'en' ? 'AI Setup Required' : 'AI সেটআপ প্রয়োজন',
      desc: language === 'en' 
        ? 'To enable AI-powered math generation, you must provide your own Gemini API Key.' 
        : 'AI-চালিত গণিত কুইজ চালু করতে আপনাকে আপনার নিজস্ব Gemini API কী প্রদান করতে হবে।',
      icon: <div className="relative">
              <Zap size={60} className="text-primary animate-pulse" />
              <div className="absolute -bottom-2 -right-2 bg-amber-500 text-white p-1.5 rounded-lg shadow-xl">
                <Key size={16} strokeWidth={3} />
              </div>
            </div>,
      color: 'bg-amber-500/10',
      tip: language === 'en' 
        ? 'Check your Profile to see how to input your GEMINI_API_KEY!' 
        : 'আপনার প্রোফাইলে গিয়ে দেখুন কীভাবে GEMINI_API_KEY ইনপুট করবেন!',
      customUI: (
        <div className="mt-4 p-4 bg-primary/5 rounded-2xl border border-primary/10 flex flex-col items-center gap-3 w-full max-w-[280px]">
           <div className="flex items-center gap-2 px-3 py-1 bg-amber-500/10 text-amber-600 rounded-full border border-amber-500/20">
             <Key size={12} className="animate-bounce" />
             <span className="text-[10px] font-black uppercase tracking-tighter">
               {language === 'en' ? 'Key Needed' : 'কী প্রয়োজন'}
             </span>
           </div>
           <p className="text-[10px] text-center opacity-70 font-bold leading-relaxed">
             {language === 'en' 
               ? 'This app uses Gemini AI. Click on your Profile icon after this tutorial to learn how to unlock all features.' 
               : 'এই অ্যাপটি Gemini AI ব্যবহার করে। সব ফিচার আনলক করতে টিউটোরিয়াল শেষে আপনার প্রোফাইল আইকনে ক্লিক করে বিস্তারিত জানুন।'}
           </p>
        </div>
      )
    }
  ];

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-6 bg-black/80 backdrop-blur-2xl"
    >
      <motion.div 
        initial={{ scale: 0.9, y: 20 }}
        animate={{ scale: 1, y: 0 }}
        className="math-card bg-surface dark:bg-slate-900 p-4 md:p-6 max-w-lg w-full relative overflow-hidden shadow-[0_0_80px_rgba(0,0,0,0.4)] border border-primary/20"
      >
        <div className="absolute -top-32 -right-32 w-64 h-64 bg-primary/20 rounded-full blur-[100px]"></div>
        <div className="absolute -bottom-32 -left-32 w-64 h-64 bg-purple-500/10 rounded-full blur-[100px]"></div>

        <AppTooltip content={language === 'en' ? 'Skip' : 'স্কিপ করুন'} position="bottom">
          <button onClick={onComplete} className="absolute top-4 right-4 p-1.5 text-muted hover:text-foreground hover:bg-black/5 dark:hover:bg-white/5 rounded-full transition-all z-20">
             <X size={20} />
          </button>
        </AppTooltip>

        <div className="relative z-10">
          <AnimatePresence mode="wait">
            <motion.div
              key={step}
              initial={{ opacity: 0, scale: 0.9, y: 10 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 1.05, y: -10 }}
              transition={{ type: "spring", damping: 25, stiffness: 120 }}
              className="flex flex-col items-center text-center gap-5"
            >
              <motion.div 
                animate={{ 
                  scale: [1, 1.03, 1],
                  rotate: [0, 2, -2, 0]
                }}
                transition={{ duration: 5, repeat: Infinity }}
                className={`w-20 h-20 rounded-2xl ${steps[step].color} flex items-center justify-center mb-0 shadow-inner ring-1 ring-white/10`}
              >
                {React.cloneElement(steps[step].icon as React.ReactElement, { size: step === 0 ? 64 : 48 })}
              </motion.div>
              <div className="space-y-2">
                <h2 className="text-xl md:text-2xl font-black tracking-tight">{steps[step].title}</h2>
                <p className="opacity-70 text-sm md:text-base leading-relaxed max-w-sm mx-auto font-medium">{steps[step].desc}</p>
                
                {(steps[step] as any).customUI}

                {steps[step].tip && (
                  <motion.div 
                    initial={{ opacity: 0, y: 5 }}
                    animate={{ opacity: 1, y: 0 }}
                    key={`tip-${step}`}
                    className="mt-3 p-3 bg-primary/5 rounded-xl border border-primary/10 flex items-center gap-2.5 max-w-xs mx-auto"
                  >
                    <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center text-primary shrink-0">
                      <Zap size={12} />
                    </div>
                    <p className="text-[9px] md:text-[10px] font-bold text-left leading-tight opacity-60 italic font-sans">
                      {steps[step].tip}
                    </p>
                  </motion.div>
                )}
              </div>
            </motion.div>
          </AnimatePresence>

          <div className="mt-8 flex flex-col md:flex-row items-center justify-between gap-5">
             <div className="flex gap-2">
               {steps.map((_, i) => (
                 <motion.div 
                   key={i} 
                   animate={{ 
                     width: i === step ? 24 : 8,
                     backgroundColor: i === step ? 'var(--primary)' : 'rgba(0,0,0,0.1)'
                   }}
                   className="h-1.5 rounded-full dark:bg-white/10" 
                 />
               ))}
             </div>
             
             <div className="flex items-center gap-3 w-full md:w-auto">
               {step > 0 && (
                 <button 
                   onClick={() => setStep(step - 1)}
                   className="flex-1 md:flex-none px-4 py-2.5 rounded-xl font-black text-xs uppercase tracking-widest opacity-50 hover:opacity-100 transition-opacity"
                 >
                   {language === 'en' ? 'Back' : 'পেছনে'}
                 </button>
               )}
               
               {step < steps.length - 1 ? (
                 <motion.button 
                   whileHover={{ scale: 1.05 }}
                   whileTap={{ scale: 0.95 }}
                   onClick={() => setStep(step + 1)}
                   className="flex-1 md:flex-none bg-primary text-white px-6 py-2.5 rounded-xl font-black text-xs uppercase tracking-widest flex items-center justify-center gap-2 shadow-lg shadow-primary/20 hover:shadow-primary/40 transition-all"
                 >
                   {t.next} <ArrowRight size={16} />
                 </motion.button>
               ) : (
                 <motion.button 
                   whileHover={{ scale: 1.05 }}
                   whileTap={{ scale: 0.95 }}
                   onClick={onComplete}
                   className="flex-1 md:flex-none bg-emerald-500 text-white px-8 py-3 rounded-xl font-black text-sm uppercase tracking-widest flex items-center justify-center gap-2 shadow-lg shadow-emerald-500/20 hover:bg-emerald-600 transition-all"
                 >
                   {t.finish} <CheckCircle size={18} strokeWidth={3} />
                 </motion.button>
               )}
             </div>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}
